spring:
  main:
    web-application-type: reactive

  application:
    name: Api-Gateway

  cloud:
    gateway:
      routes:
        - id: Academic-Service
          uri: lb://Academic-Service
          predicates:
            - Path=/api/academic/**

        - id: Payment-Service
          uri: lb://Payment-Service
          predicates:
            - Path=/api/payment/**

        - id: Discovery-Server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: Discovery-Server-Static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/Microservice-Test-Realm

#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#Tracing
management:
  tracing:
    sampling:
      probability: 1.0
