version: '3'
services:
  database:
    container_name: asqaula_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: asquala
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asquala-net

  service-discovery:
    image: $HARBOR_URL/kft-lab/service-discovery
    ports:
      - 8761:8761
    networks:
      - asquala-net

  academic-service:
    image: $HARBOR_URL/kft-lab/academic-service
    ports:
      - "0:0"
    networks:
      - asquala-net
    depends_on:
      - service-discovery

  payment-service:
    image: $HARBOR_URL/kft-lab/payment-service
    ports:
      - "0:0"
    networks:
      - asquala-net
    depends_on:
      - service-discovery

  api-gateway:
    image: $HARBOR_URL/kft-lab/api-gateway
    ports:
      - 8181:8181
    networks:
      - asquala-net
    depends_on:
      - service-discovery

networks:
  asquala-net:
    driver: bridge

volumes:
  postgres_data:
